# Generated by Django 4.1.2 on 2022-11-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(default='available', max_length=9),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['available', 'pending', 'sold'])), name='valid_status'),
        ),
    ]
